; PlatformIO Project Configuration File

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

; Nếu dùng board khác:
; board = d1_mini       ; Wemos D1 Mini
; board = esp12e        ; ESP-12E
; board = esp01_1m      ; ESP-01

monitor_speed = 115200
upload_speed = 921600
monitor_dtr = 0
monitor_rts = 0

lib_deps = 
    knolleary/PubSubClient@^2.8
    sandeepmistry/LoRa@^0.8.0
    bblanchon/ArduinoJson@^6.21.3
    ESP8266WiFi

build_flags = 
    -D ARDUINO_ARCH_ESP8266
    -D MQTT_MAX_PACKET_SIZE=512
    -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY
