DROP TABLE IF EXISTS tbl_survey_points CASCADE;
DROP TABLE IF EXISTS tbl_mcus CASCADE;
DROP TABLE IF EXISTS tbl_farm_users CASCADE;
DROP TABLE IF EXISTS tbl_farms CASCADE;
DROP TABLE IF EXISTS tbl_users CASCADE;
DROP TABLE IF EXISTS tbl_sensor_data CASCADE;
DROP TABLE IF EXISTS tbl_device_commands CASCADE;